# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Gather Information
  jobs:
  - job:
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'Azure subscription 1 (6add6a10-e330-415e-a37d-2ee5ab0ab8eb)'
        KeyVaultName: 'secrets-and-certs'
        SecretsFilter: '*'
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      # - task: AzureKeyVault@1
      #   inputs:
      #     azureSubscription: 'Azure subscription 1(6add6a10-e330-415e-a37d-2ee5ab0ab8eb)'
      #     KeyVaultName: 'secrets-and-certs'
      #     SecretsFilter: '*'
      #     RunAsPreJob: false
      - task: Docker@2
        inputs:
          containerRegistry: 'Patryk Rubaj Docker Hub'
          command: 'login'
          arguments: '--username patrykrubaj --password $(DockerHubAccessToken)'
      - task: Docker@2
        inputs:
          containerRegistry: 'Patryk Rubaj Docker Hub'
          repository: 'patrykrubaj/quantumbudget-frontend'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest