version: "3.8"
services:
  mongodatabase:
    build: ./mongodb
    command: mongod --bind_ip_all --noauth
    restart: always
    ports:
      - "5005:27017"
    environment:
      MONGO_INITDB_DATABASE: QuantumBudget
  stripe_cli:
    image: stripe/stripe-cli
    command: ["listen", "--forward-to", "http://backend/payments/stripe-webhook", "--api-key", "${Stripe__SecretKey}"]
  backend:
    build: .
    depends_on:
      - mongodatabase
      - stripe_cli
    ports:
    - "5001:443"
    - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      MongoDBConnectionString: ${MongoDBConnectionString}
      MongoDBBudgetsCollectionName: ${MongoDBBudgetsCollectionName}
      MongoDBDatabaseName: ${MongoDBDatabaseName}
      Auth0__Instance: ${Auth0__Instance}
      Auth0__TenantId: ${Auth0__TenantId}
      Auth0__Audience: ${Auth0__Audience}
      Auth0__ClientId: ${Auth0__ClientId}
      Auth0__ClientSecret: ${Auth0__ClientSecret}
      Stripe__Domain: ${Stripe__Domain}
      Stripe__PublicKey: ${Stripe__PublicKey}
      Stripe__SecretKey: ${Stripe__SecretKey}
      Stripe__WebhookSecret: ${Stripe__WebhookSecret}
      GoogleApiCredentials__ClientId: ${GoogleApiCredentials__ClientId}
      GoogleApiCredentials__ClientSecret: ${GoogleApiCredentials__ClientSecret}
      Mailchimp__ApiUrl: ${Mailchimp__ApiUrl}
      Mailchimp__ApiKey: ${Mailchimp__ApiKey}
      Mailchimp__AudienceId: ${Mailchimp__AudienceId}
      Mailchimp__MarketingPermissionIdForEmail: ${Mailchimp__MarketingPermissionIdForEmail}